yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
]

yatube/users/urls.py
from django.contrib.auth.views import (LoginView,
                                       LogoutView,
                                       PasswordChangeView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView,
                                       PasswordChangeDoneView
                                       )


from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('logout/',
         LogoutView.as_view(template_name='users/logged_out.html'),
         name='logout'
         ),
    path('login/',
         LoginView.as_view(template_name='users/login.html'),
         name='login'
         ),
    path('password_change/',
         PasswordChangeView.as_view(
             template_name='users/password_change_form.html'),
         name='password_change'
         ),
    path('password_change_done/',
         PasswordChangeDoneView.as_view(
             template_name='users/password_change_done.html'),
         name='password_change_done'
         ),
    path('password_reset_form/',
         PasswordResetView.as_view(
             template_name='users/password_reset_form.html'),
         name='password_reset_form'
         ),
    path('password_reset/done/',
         PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'),
         name='password_reset_done'
         ),
    path('reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'
         ),
    path('password_reset_complete/',
         PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.htnl'),
         name='password_reset_complete'
         ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True, db_index=True, verbose_name="URL")
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Введите текст поста',
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор поста',
    )
    group = models.ForeignKey(
        Group,
        blank=True, null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост',
    )

    class Meta:
        ordering = ('-pub_date',)

    def __str__(self):
        return self.text[:15]

yatube/posts/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group')

        help_texts = {
            'text': 'Текст нового пост',
            'group': 'Группа, к которой будет относиться пост',
        }

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth import get_user_model


User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect

from django.contrib.auth.decorators import login_required

from django.db.models.functions import Length


from .models import Post, Group, User

from .forms import PostForm

from .paginator import get_page


def index(request):
    posts = Post.objects.all().select_related('author', 'group').annotate(
        text_length=Length('text')
    )
    page_obj = get_page(request, posts)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.select_related('author').annotate(
        text_length=Length('text')
    )
    page_obj = get_page(request, posts)
    context = {
        'page_obj': page_obj,
        'group': group,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(
        User.objects.prefetch_related('posts', 'posts__group'),
        username=username
    )
    page_obj = get_page(request, author.posts.all())
    context = {
        'author': author,
        'page_obj': page_obj,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(
        Post.objects.select_related('author', 'group'),
        id=post_id
    )
    context = {'post': post}
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):

    form = PostForm(request.POST or None)
    if not request.method == 'POST':
        return render(request, 'posts/create_post.html', {'form': form})

    if not form.is_valid():
        return render(request, 'posts/create_post.html', {'form': form})

    post = form.save(commit=False)
    post.author = request.user
    post.save()
    return redirect('posts:profile', username=request.user)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)

    if post_id and request.user != post.author:
        return redirect('posts:post_detail', post_id=post_id)
    form = PostForm(request.POST or None, instance=post)

    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)

    context = {
        'form': form,
        'post': post,
        'is_edit': True,
    }
    return render(request, 'posts/create_post.html', context)

yatube/users/views.py
from django.views.generic import CreateView

from django.urls import reverse_lazy

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/about/author.html
{% extends "base.html" %}
{% load static %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
<h2>Привет, я автор, меня зовут Кулабухов Федор.</h2>
<ul>
<li> 
 <a href="https://github.com/Fedor-new-Hope">GitHub</a>
</li>
<li>
 <a href="https://vk.com/id11507817 ">VK.com</a>
</li>
</ul>

<p>
  <h5>Немного вдохновляющих цитат :</h5>
</p>
<p>    
  <em> "Я не вошебник я только учусь..."</em>  Е.Шварц
</p>
<p>
  <em> "Дорогу осилит идущий..."  </em> народная мудрость
</p>
<p>
  <em> " - А я смогу<br> - А он такой<br> - А я упрямый<br> - Он такой<br> - Я труфальдино из Бергамо, я такой<br> - Он Труфальдино из Бергамо "</em>  к.ф Труфальдино из Бергамо.   
</p>
<p>
  <h5>Мое рабочее окружение :</h5>
<p>  
<img src= "{% static 'img/table.jpg' %}" alt="Рабочий стол" width="600" height="450"/>
<img src= "{% static 'img/windowsill.jpg' %}" alt="Трибуна потдержки" width="600" height="450"                                      />

{% endblock %} 

yatube/templates/about/tech.html
<!-- templates/about/tech.html -->
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
{% comment %} Колонки с отступом сверху и снизу {% endcomment %}
<div class="row">
  <h1>Вот что я умею</h1>
  {% comment %}
    Боковой блок со списком технологий 
    Займет всю ширину блока на мобильном
    и 25% при размерах экрана ≥768px
  {% endcomment %}
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Python
      </li>
      <li class="list-group-item">
        Django
      </li>
    </ul>
  </aside>
  {% comment %}
    Статья  
    Займет всю ширину блока на мобильном
    и 75% при размерах экрана ≥768px
  {% endcomment %}
  <article class="col-12 col-md-9">
    <p>Технологии в процессе изучения))</p>
  </article>
</div>
{% endblock %}

yatube/templates/base.html
<!DOCTYPE html> 
<html lang="ru"> 
 <head>
{% load static %}        

  <meta charset="utf-8"> 
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" href="{% static 'img/fav/fav.ico' %}" type="image">
  <link rel="apple-touch-icon" sizes="180x180"
  href="{% static 'img/fav/apple-touch-icon.png'  %}">
  <link rel="icon" type="image/png" sizes="32x32"
  href="{% static 'img/fav/favicon-32x32.png' %}">
  <link rel="icon" type="image/png" sizes="16x16"
  href="{% static 'img/fav/favicon-16x16.png' %}">
  <meta name="msapplication-TileColor" content="#000">
  <meta name="theme-color" content="#ffffff">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <title>
  {% block title %}
  {% endblock %} 
  </title>
  </head>
  
{% include 'includes/header.html'%}    
<div class="container py-5"> 
  {% block content %}
  {% endblock %}
</div>   
{% include 'includes/footer.html' %}        
</html>   

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <h4>© {{ year }} Copyright <span style="color:fuchsia">Ya</span>tube</h4>      
</footer>

yatube/templates/includes/header.html
{% load static %}
<header>
  {% with request.resolver_match.view_name as view_name %}
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:fuchsia">Ya</span>tube
      </a>
      <ul class="nav nav-pills">
        <li class="nav-item"> 
          <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}" 
          href="{% url 'about:author' %}">
         Об авторе
       </a>
        </li>
        <li class="nav-item">
          <a class="nav-link  {% if view_name  == 'about:tech' %}active{% endif %}" 
          href="{% url 'about:tech' %}">
          Технологии</a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item"> 
          
            <a class="nav-link {% if view_name  == 'posts:post_create'  %}active{% endif %}"
            href="{% url 'posts:post_create'   %}">Новая запись</a>
          
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name  == 'users:password_change' %}active{% endif %}"
           href="{% url 'users:password_change' %}">Изменить пароль</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name  == 'users:logout' %}active{% endif %}"
           href="{% url 'users:logout' %} ">Выйти</a>
        </li>
        <li>
          Пользователь: {{ user.username }}
        </li>
        {% else %}
        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name  == 'users:login' %}active{% endif %}"
           href="{% url 'users:login' %}">Войти</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name  == 'users:signup' %}active{% endif %}"
           href="{% url 'users:signup' %}">Регистрация</a>
        </li>
        {% endif %}
      </ul>
      {% endwith %}
    </div>
  </nav>      
</header> 

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}{% if is_edit %}Редактировать пост{% else %}Новый пост{% endif %}{% endblock %}
{% block content %}

    <main>
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">  
              {% if is_edit %}Редактировать пост{% else %}     
                Новый пост
              {% endif %}               
              </div>
              <div class="card-body">
                {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
              {% endif %}
              <form method="post" action="{% url 'posts:post_create' %} ">
              {% csrf_token %}
              {% for field in form %}
                <div class="form-group row my-3"
                  {% if field.field.required %} 
                   aria-required="true"
                   {% else %}
                   aria-required="false"
                  {% endif %} >
                <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
                </label>
                {{ field }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
                </div>
                {% endfor %}
                <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-outline-primary">
                {% if is_edit %}
                Сохранить
                {% else %}
                Добавить
               {% endif %} 
             </button>
            </div>
           </form>
          </div>
        </div>
      </div>
      </div>
    </div>
  </main>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}Записи сообщества {{ group.title }}{% endblock %}
  {% block content %}
    <h1> {{ group.title }} </h1>
    <p>{{ group.description|linebreaksbr }}</p>
    {% for post in page_obj %}
    {% include 'posts/includes/page_body.html' %} 
    {% if post.group %}
      <a href="{% url 'posts:profile' post.author %}">Профиль автора: "{{ post.author.get_full_name }}"</a>
      <!-- Добрый день, Антон, не совсем понятно каких ссылок не хватает, в тз их не было. Исходя из разумных соображений прикрутил эту. -->
    {% endif %}        
    {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}   
   
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

 

yatube/templates/posts/includes/page_body.html
  <ul>
    <li>
    Автор: {{ post.author.get_full_name }} 
    </li>
    <li>
    Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>      
  <p>
  {{ post.text|linebreaksbr }}
  </p>
  
  

yatube/templates/posts/index.html
{% extends "base.html" %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
  <h1>Последние обновления на сайте</h1>
  {% for post in page_obj %}
  {% include 'posts/includes/page_body.html' %} 
  {% if post.group %}
    <a href="{% url 'posts:group_list' post.group.slug %}">Все записи группы "{{ post.group.title }}"</a>
  {% endif %}        
  {% if not forloop.last %}<hr>{% endif %}
  {% endfor %} 
   
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% block title %} {{ post.text|truncatechars:30 }} {% endblock %}
{% block content %}
  <body>	   
    <main>
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
            {% if post.group %}
            <li class="list-group-item">
              Группа: {{ post.group.title }}
              <a href="{% url 'posts:group_list' post.group.slug %}">
              все записи группы
              </a></li> 
              {% endif %}            
              <li class="list-group-item">
                Автор: {{ post.author.get_full_name }}
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center">
                Всего постов автора:  <span >{{ post.author.posts.count }}</span>
              </li>
              <li class="list-group-item">
                <a href="{% url 'posts:profile' post.author.username %}">
                  все посты пользователя
                </a>
              </li>
            </ul>
          </aside>
          <article class="col-12 col-md-9">
             <p> {{ post.text|linebreaksbr }}</p>                             
        </div>
        {% if post.author == request.user %}
        <a class="btn btn-outline-primary" href="{% url 'posts:post_edit' post.pk %}">
          редактировать запись
        </a>
        {% else %}
        {% endif %}  
      </div>
    </main>
    </body>
{% endblock %}   

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% block title %}{{ author.get_full_name }} профайл пользователя{% endblock %}
{% block content %}
  <div class="container py-5">        
  <h1>Все посты пользователя: {{ author.get_full_name }} </h1>
  <h3>Всего постов: {{ author.posts.count }} </h3> 
  {% for post in page_obj %}
    <article>
      <ul>
        <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }} 
        </li>
      </ul>
      <p>{{ post.text|linebreaksbr }}</p>
      <a href="{% url 'posts:post_detail'  post.id %} ">подробная информация</a>
      </article>
        {% if post.group %}       
          <a href="{% url 'posts:group_list' post.group.slug %}">Все записи группы </a>
          {% endif %}
          {% if not forloop.last %}<hr>{% endif %}
          {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %} 

yatube/templates/users/login.html
{% extends 'base.html' %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justufy-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}        
                <div class="alert alert-danger">
                  {{ error|escape }}  
                </div>  
              {% endfor %}  
            {% endfor %}  
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}    
          {% endif %}  

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}      

          {% for field in form %}
          <div class="form-group row my-3"
          {% if field.field.required %} 
            aria-required="true"
          {% else %}
            aria-required="false"
          {% endif %}
        >
          <label for="{{ field.id_for_label }}">
            {{ field.label }}
              {% if field.field.required %}
                <span class="required text-danger">*</span>
              {% endif %}
          </label>
          <div>
          {{ field|addclass:'form-control' }}
            {% if field.help_text %}
              <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                {{ field.help_text|safe }}
              </small>
            {% endif %}
          </div>
        </div>
      {% endfor %}
      <div class="col-md-6 offset-md-4">
        <button type="submit" class="btn btn-primary">
          Войти
        </button>
        <a href="{% url 'users:password_reset_form' %}" class="btn btn-link">
          Забыли пароль?
        </a>
      </div>
      </form>
    </div> 
  </div> 
</div> 
</div> 
{% endblock %} 
             

yatube/templates/users/password_change_form.html
{% extends 'base.html' %}
{% block title %}Изменение пароля{% endblock %}
{% block content %}
  <body>	   
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Изменить пароль
              </div>
              <div class="card-body">
                <form method="post" action={% url 'users:password_change' %}>
                  {% csrf_token %}
                  <div class="form-group row my-3 p-3">
                    <label for="id_old_password">
                      Старый пароль
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="password" name="old_password" autofocus class="form-control" required id="id_old_password">
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password1">
                      Новый пароль
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="password" name="new_password1" class="form-control" required id="id_new_password1">
                      <small id="id_new_password1-help" class="form-text text-muted">
                        <ul><li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li><li>Ваш пароль должен содержать как минимум 8 символов.</li><li>Ваш пароль не может быть одним из широко распространённых паролей.</li><li>Ваш пароль не может состоять только из цифр.</li></ul>
                      </small>
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password2">
                      Подтверждение нового пароля
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="password" name="new_password2" class="form-control" required id="id_new_password2">
                  </div>
                  <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                      Изменить пароль
                    </button>
                  </div>
                </form>
              </div> 
            </div> 
          </div> 
      </div>
    </main>
{% endblock %}    

yatube/templates/users/password_reset_complete.html
<!DOCTYPE html> 
{% extends 'base.html' %}
{% block title %}Сброс пароля прошёл успешно{% endblock %}
{% block content %}
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Восстановление пароля завершено
              </div>
              <div class="card-body">
                <p>Ваш пароль был сохранен. Используйте его для входа</p>
                <a href="{% url 'users:login' %}">войти</a>
              </div> 
            </div> 
          </div>
        </div> 
      </div>
    </main>
{% endblock %}

yatube/templates/users/password_reset_confirm.html
{% extends 'base.html' %}
{% block title %}Новый пароль{% endblock %}
{% block content %} 

    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Введите новый пароль
              </div>
              <div class="card-body">
                <form method="post" action="{% url 'users:password_reset_confirm' %}">
                  {% csrf_token %}
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password1">
                      Новый пароль        
                      <span class="required text-danger">*</span>        
                    </label>    
                    <input type="password" name="new_password1" class="form-control" required id="id_new_password1">      
                    <small id="id_new_password1-help" class="form-text text-muted">
                      <ul><li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li><li>Ваш пароль должен содержать как минимум 8 символов.</li><li>Ваш пароль не может быть одним из широко распространённых паролей.</li><li>Ваш пароль не может состоять только из цифр.</li></ul>
                    </small>      
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password2">
                      Подтверждение нового пароля        
                      <span class="required text-danger">*</span>        
                    </label>    
                    <input type="password" name="new_password2" class="form-control" required id="id_new_password2">      
                  </div>
                  <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                      Назначить новый пароль
                    </button>
                  </div>
                </form>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row -->
  
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Ошибка
              </div>
              <div class="card-body">
                <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row -->
   
      </div>
    </main>
{% endblock %}

yatube/templates/users/password_reset_form.html
<!DOCTYPE html> 
{% extends 'base.html' %}
{% block title %}Сброс пароля{% endblock %}
{% block content %}
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы регистрировались
              </div>
              <div class="card-body"> 
                <form method="post" action="{% url 'users:password_reset_form' %}">
                  {% csrf_token %}
                  
                  <div class="form-group row my-3 p-3">
                    <label for="id_email">
                      Адрес электронной почты
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="email" name="email" maxlength="254" class="form-control" required id="id_email">
                  </div>
                  <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                      Сбросить пароль
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>  
      </div>
    </main>

	  </body>
</html>
{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}

{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
          {% load user_filters %} {# Загружаем фильтры #}
              {% if form.errors %}
                  {% for field in form %} 
                    {% for error in field.errors %}            
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}

              <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}

              {% for field in form %} 
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>

                  {{ field|addclass:'form-control' }} 
                    {% if field.help_text %}
                      <small 
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted"
                      >
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}